{
 "title": "Build - Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "build_id",
    "label": "Build Reference",
    "query": "SELECT id AS value, project || ' - ' || tag AS label\nFROM build_reports\nORDER BY timestamp DESC;\n"
   }
  ]
 },
 "panels": [
  { "title": "Latest Build Summary", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE \n    WHEN EXISTS (\n      SELECT 1\n      FROM trivy_results tr\n      JOIN build_reports br ON tr.build_id = br.id\n      WHERE br.id = $build_id\n        AND tr.severity IN ('HIGH','CRITICAL')\n    ) \n    THEN 0 \n    ELSE 1 \n  END AS status;\n"
    }
   ]
  },
  {
   "title": "Build Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT br.tag \nFROM build_reports br\nWHERE br.id= '$build_id'\n"
    }
   ]
  },
  {
   "title": "Build Reference Id",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT br.id \nFROM build_reports br\nWHERE br.id= '$build_id'\n"
    }
   ]
  },
  {
   "title": "✅ Approved Exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS total_critical\nFROM trivy_results tr\nWHERE tr.build_id = '$build_id'\n  AND tr.is_exception=1;\n"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Severity",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    br.timestamp AS time,\n    tr.severity AS metric,\n    COUNT(*) AS value\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE br.id = '$build_id' AND tr.is_exception=0\nGROUP BY br.timestamp, tr.severity\n\nUNION ALL\n\nSELECT \n    br.timestamp AS time,\n    'CRITICAL' AS metric,   -- Force secrets into CRITICAL bucket\n    COUNT(*) AS value\nFROM trivy_secrets ts\nJOIN build_reports br ON ts.build_id = br.id\nWHERE br.id = '$build_id'\n  AND ts.severity = 'CRITICAL'\nGROUP BY br.timestamp\n\nORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    br.id AS build_id,\n    br.image,\n    br.tag,\n    br.ci_url,\n    br.timestamp,\n\n   -- Count vulnerabilities by severity\n    COUNT(*) FILTER (WHERE tr.severity = 'CRITICAL' AND tr.is_exception=0) AS critical_count,\n    COUNT(*) FILTER (WHERE tr.severity = 'HIGH' AND tr.is_exception=0)     AS high_count,\n    COUNT(*) FILTER (WHERE tr.severity = 'MEDIUM' AND tr.is_exception=0)   AS medium_count,\n    COUNT(*) FILTER (WHERE tr.severity = 'LOW' AND tr.is_exception=0)      AS low_count,\n    COUNT(*) FILTER (WHERE tr.severity IS NULL OR tr.severity = '' AND tr.is_exception=0) AS unknown_count,\n    COUNT(*) FILTER (WHERE tr.is_exception=1)  AS exception_count,\n\n    -- Total vulnerabilities and secrets\n    COUNT(DISTINCT tr.id) AS total_vulnerabilities,\n    COUNT(DISTINCT ts.id) AS total_secrets\n\nFROM build_reports br\nLEFT JOIN trivy_results tr ON tr.build_id = br.id\nLEFT JOIN trivy_secrets ts ON ts.build_id = br.id\n\nWHERE br.id = '$build_id'\nGROUP BY br.id, br.image, br.tag, br.ci_url, br.timestamp;\n"
    }
   ]
  },
  {
   "title": "🔴 Secrets Exposed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS secret_count\nFROM trivy_secrets\nWHERE build_id = $build_id;\n"
    }
   ]
  },
  {
   "title": "🔴 Critical Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS total_critical\nFROM trivy_results tr\nWHERE tr.build_id = '$build_id'\n  AND tr.severity = 'CRITICAL' AND tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "🟠 High Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS total_critical\nFROM trivy_results tr\nWHERE tr.build_id = '$build_id'\n  AND tr.severity = 'HIGH' AND tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "🟡 Medium Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS total_critical\nFROM trivy_results tr\nWHERE tr.build_id = '$build_id'\n  AND tr.severity = 'MEDIUM' AND tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "🟢 Low Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT COUNT(*) AS total_critical\nFROM trivy_results tr\nWHERE tr.build_id = '$build_id'\n  AND tr.severity = 'LOW' AND tr.is_exception=0;\n"
    }
   ]
  },
  {
   "title": "Secrets Exposed",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    ts.target AS file_name,\n    ts.rule_id,\n    ts.category,\n    ts.severity,\n    ts.title,\n    ts.match,\n    ts.timestamp\nFROM trivy_secrets ts\nWHERE ts.build_id = '$build_id'\nORDER BY ts.timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Vulnerabilities List",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    tr.vuln_id,\n    tr.pkg_name,\n    tr.installed,\n    tr.fixed,\n    tr.severity,\n    tr.status,\n    tr.primary_url,\n    tr.timestamp\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE tr.build_id = '$build_id' AND tr.is_exception=0\nORDER BY tr.severity DESC, tr.vuln_id;\n"
    }
   ]
  },
  {
   "title": "⚠️ Ignored Vulnerabilities (Approved Exceptions)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT \n    tr.vuln_id,\n    tr.pkg_name,\n    tr.installed,\n    tr.fixed,\n    tr.severity,\n    tr.status,\n    tr.primary_url,\n    tr.timestamp\nFROM trivy_results tr\nJOIN build_reports br ON tr.build_id = br.id\nWHERE tr.build_id = '$build_id' AND tr.is_exception=1\nORDER BY tr.severity DESC, tr.vuln_id;\n"
    }
   ]
  },
  {
   "title": "AI Recommendations",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "dataset": "cve_db",
     "rawSql": "SELECT br.ai_recommendation\nFROM build_reports br\nWHERE br.id= '$build_id'\n"
    }
   ]
  }
 ]
}